# Generated by Django 5.2.4 on 2025-07-18 09:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('anxiety', 'Anxiety Disorders'), ('depression', 'Depression'), ('trauma', 'Trauma & PTSD'), ('relationships', 'Relationship Counseling'), ('addiction', 'Addiction Recovery'), ('grief', 'Grief & Loss'), ('eating_disorders', 'Eating Disorders'), ('bipolar', 'Bipolar Disorder'), ('ocd', 'OCD'), ('adhd', 'ADHD'), ('family_therapy', 'Family Therapy'), ('child_therapy', 'Child & Adolescent Therapy'), ('general', 'General Mental Health')], max_length=50)),
                ('experience_years', models.IntegerField(help_text='Years of professional experience', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('location', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Professional biography')),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('available_days', models.CharField(blank=True, help_text='Comma-separated list of available days', max_length=100)),
                ('available_times', models.CharField(blank=True, help_text='Available time slots (e.g., 9:00-17:00)', max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Therapist Profile',
                'verbose_name_plural': 'Therapist Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
