# Generated by Django 5.2.4 on 2025-07-22 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('therapists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('appointment_request', 'New Appointment Request'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_completed', 'Session Completed'), ('appointment_cancelled', 'Appointment Cancelled'), ('message_received', 'New Message Received'), ('profile_updated', 'Profile Updated'), ('availability_updated', 'Availability Updated'), ('client_registered', 'New Client Registered')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
                ('related_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='therapists.therapistprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
