# Generated by Django 5.2.3 on 2025-07-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindcare_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
