# Generated by Django 5.2.4 on 2025-07-25 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(default='general'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('assessment', 'Assessment'), ('message', 'Message'), ('crisis', 'Crisis Alert'), ('system', 'System')], default='general', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('appointment_reminder_hours', models.PositiveIntegerField(default=24, help_text='How many hours before appointment to send reminder')),
                ('assessment_alert_threshold', models.PositiveIntegerField(default=15, help_text='Assessment scores above this will trigger alerts')),
                ('crisis_notification_recipients', models.ManyToManyField(help_text='Staff who receive crisis notifications', limit_choices_to={'role': 'admin'}, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Settings',
            },
        ),
    ]
